export const superNames: Record<string, string> = {
  rock:"Rock",
  cactus:"Cactus",
  ladybug:"Ladybug",
  bee:"Bee",
  ant_baby:"Baby Ant",
  ant_worker:"Worker Ant",
  ant_soldier:"Soldier Ant",
  ant_queen:"Queen Ant",
  ant_hole:"Ant Hole",
  beetle:"Beetle",
  hornet:"Hornet",
  centipede:"Centipede",
  centipede_evil:"Centipede",
  centipede_desert:"Centipede",
  square:"Square",
  ladybug_dark:"Ladybug",
  ladybug_shiny:"Ladybug",
  spider:"Spider",
  scorpion:"Scorpion",
  fire_ant_soldier:"Soldier Fire Ant",
  fire_ant_burrow:"Fire Ant Burrow",
  sandstorm:"Sandstorm",
  bubble:"Bubble",
  bumble_bee:"Bumble Bee",
  shell:"Shell",
  starfish:"Starfish",
  crab:"Crab",
  jellyfish:"Jellyfish",
  digger:"Digger",
  sponge:"Sponge",
  leech:"Leech",
  dandelion:"Dandelion",
  fire_ant_baby:"Baby Fire Ant",
  fire_ant_worker:"Worker Fire Ant",
  fire_ant_queen:"Queen Fire Ant",
  ant_egg:"Ant Egg",
  fire_ant_egg:"Fire Ant Egg",
  fly:"Fly",
  leafbug:"Leafbug",
  mantis:"Mantis",
  termite_baby:"Baby Termite",
  termite_worker:"Worker Termite",
  termite_soldier:"Soldier Termite",
  termite_overmind:"Termite Overmind",
  termite_mound:"Termite Mound",
  termite_egg:"Termite Egg",
  bush:"Bush",
  roach:"Roach",
  moth:"Moth",
  firefly:"Firefly",
  beetle_hel:"Hel",
  wasp:"Wasp",
  spider_hel:"Hel",
  centipede_hel:"Hel",
  wasp_hel:"Hel",
  gambler:"Gambler",
  firefly_magic:"Firefly",
  beetle_nazar:"Beetle",
  worm:"Worm",
  mecha_flower:"Mecha Flower",
  wasp_mecha:"Wasp",
  spider_mecha:"Spider",
  leafbug_shiny:"Leafbug",
  crab_mecha:"Crab",
  barrel:"Barrel",
  beetle_mummy:"Beetle",
  beetle_pharaoh:"Beetle",
  tomb:"Tomb",
};